### PR TITLE
Concurrent Incidents

### PR DESCRIPTION
**Pull request by bliitzkrieg**
## Overview
Added ability to toggle concurrent incidents on map inside Incident analysis view

## GitHub Issues
-  #481 

## Changes
- N/A

## Screenshots / Videos
Screen Shot 2020-06-16 at 8 56 06 PM
Screen Shot 2020-06-16 at 8 56 09 PM

## Steps to Test
- Find incident in incident analysis with concurrent incidents
- Scroll to Map
- Click Layer button to toggle them on
- Search around map to find concurrent incidents

### CODE REVIEW

**Comment by bliitzkrieg** [comment]
@chopchop505 Should be good for merge. Do you want to use a different icon for the toggle?

**Comment by larskendall** [comment]
I noticed one more thing that should probably be adjusted...

Right now the styling for the incident map component is mixed in the incident analysis page's css (`incident-analysis.scss`), but I think that probably belongs in a file specifically for the incident map component, so that it's reusable (since it's essentially default styling for those elements in the component). Otherwise you'd have to set the styling for `.incident-map-container` and `.incident-map-concurrent-layer` again for any page where you want to reuse that stuff.

**Comment by bliitzkrieg** [comment]
Should be good for review

**Comment by bliitzkrieg** [comment]
Should be good for review

**Comment by larskendall** [comment]
Looks great! I'll merge it in.

**Pull request merged**
