### PR TITLE
erf mvp

### PR DESCRIPTION
**Pull request by chopchop505**

### CODE REVIEW

**Comment by chopchop505** [comment]
You need Delray data to test, please PM is you need

**Comment by chopchop505** [comment]
image
image
image

**Comment by larskendall** [comment]
@chopchop505 I don't have data for this yet to test the graph, but I did a pass on the copy in the meantime. There were just a few little typo type things I noticed.

## Historic ERF Analysis
Screen Shot 2019-12-04 at 6 43 12 AM

- "expore" should be "explore"
- "To try out the tool..." line should have a period at the end
- The email address should probably be set to not wrap
- There's a space missing after the email address
- "singals" should be "signals"

## How to read this
Screen Shot 2019-12-04 at 7 06 57 AM

- Maybe unlikely, but "minutes" should be singular if the value in front is 1.
- "has" should be "have" (unless there's only 1 incident, in which case "incidents" should also be singular)
- I think this line should be more like, "This highlights when your currently configured ERF has been met (when at least # personnel have arrived on scene)."
- I guess there should be periods at the ends of the bold lines, since they're proper sentences.

**Comment by chopchop505** [comment]
@larskendall thanks - I'm going to merge and deploy.  Feel free to test in prod, and write any bugs.  I'm not going to advertise the new feature for a week or so, and its not obvious so I doubt any user will even see it yet.

**Pull request merged**
