### PR TITLE
Update misleading text in subscription canceled modal.

### PR DESCRIPTION
**Pull request by larskendall**
The issue with the text is explained here https://github.com/statengine/stat-engine/issues/189

## Before
selection_156

## After
selection_155

### CODE REVIEW

**Comment by garnertb** [comment]
This potentially restricts the user from fixing the problem themselves.  Would changing the modal Manage Subscription text to a link that went to the manage subscription section alleviate both concerns?

**Comment by larskendall** [comment]
@garnertb The main problem was that even if they visit the Manage Subscription page there's currently no way for them to reactivate their subscription (in test mode at least). Here's what it looks like at the moment...

selection_158

I looked into it a bit more, since it sounds like we definitely want them to be able to reactivate their subscription themselves, and it looks like that's just a configuration option in the Chargebee admin console. So I was able to activate that setting for test mode. Maybe it was a discrepancy between test and production modes... I'll look into it some more. But is this definitely something we want enabled? It looks like this with the setting turned on...

selection_157

**Comment by larskendall** [comment]
@garnertb I think making "Manage Subscription" a link will be a good solution to the navigation issue by the way.

**Comment by larskendall** [comment]
@garnertb This should be fixed as of 7c33c84c268517f48d68d6fd90111e3047d37e4d. I turned "Manage Subscription" into a link in the modal text and enabled the Chargebee setting in test mode for users to be able to reactivate their canceled subscription. That setting just needs to be activated in production mode (which I think you've already done) and we should be good to go.

**Pull request merged**
