### PR TITLE
Add a new simultaneous-incidents dashboard

### PR DESCRIPTION
**Pull request by andersonad**
This is a dashboard designed to show off the features of the simultaneous-incidents functionality.
resolves https://github.com/ProminentEdge/ES-simultaneous-update/issues/5

### CODE REVIEW

**Comment by chopchop505** [comment]
I'm not sure if this is the appropriate place to leave this bug, but I think there may be bugs either in the algorithm, in our existing way of detecting overlapping(concurrent).    

I would expect these numbers to be the same:
http://localhost:3000/incidents/F01812150063

image

image

**Comment by chopchop505** [comment]
In seemed to work for most incidents, but I just caught this one by poking around.

**Comment by chopchop505** [comment]
Default zoom level is not set.  

image

If i recall this was fixed in another PR.  If so, disregard

**Comment by chopchop505** [comment]
image
 Capitlaize general

**Comment by chopchop505** [comment]
image

I feel like this might get too busy when there are hundreds of stations like Miami-Dade.  What do you think?

**Comment by chopchop505** [comment]
image

when one more incident "is opened" I think would be better terminology.  An incident doesn't really "arrive"

**Comment by chopchop505** [comment]
image

Would that actually fix the problem?

**Comment by andersonad** [comment]
> In seemed to work for most incidents, but I just caught this one by poking around.
> The query we run is located to determine concurrent incidents is at: https://github.com/StatEngine/stat-engine/blob/master/server/api/incident/incident.controller.js#L183
> 
> Maybe you are including active or suppressed incidents?

You are correct, the script was including suppressed incidents. I updated it to exclude suppressed and got the right number.

**Comment by andersonad** [comment]
> image
> 
> Would that actually fix the problem?

In terms of graph visualization, yes. Since they are visualizing the maximum observed values, and we know some departments can have outrageous outliers (Tucson once had a 2 million second turnout time), such a filter would "cap" the observed maximums to render the patterns in the data more observable. Realistically, they should select the maximum value they feel represents a valid incident duration. In a few of the standards of cover reports I've read, the departments would filter out incidents that were longer in duration than some arbitrary time, and I saw 60 minutes at least once, so it became my ballpark value. If we want to change that value or put a bigger disclaimer on it we can do so.

**Comment by chopchop505** [comment]
> In terms of graph visualization, yes. Since they are visualizing the maximum observed values, and we know some departments can have outrageous outliers (Tucson once had a 2 million second turnout time), such a filter would "cap" the observed maximums to render the patterns in the data more observable. Realistically, they should select the maximum value they feel represents a valid incident duration. In a few of the standards of cover reports I've read, the departments would filter out incidents that were longer in duration than some arbitrary time, and I saw 60 minutes at least once, so it became my ballpark value. If we want to change that value or put a bigger disclaimer on it we can do so.

Yeah I was referring to the number of overlapping/in_progress. Applying a filter is not actually going to fix those numbers, it'll just adjust the view of the chart.

**Pull request merged**
