### PR TITLE
Workspaces

### PR DESCRIPTION
**Pull request by chopchop505**
Sorry for the monstrosity.   This PR introduces the concept of workspaces.  A workspace, is simply a new tenancy, or kibana index.  This allows users to create their own dashboards, and visualizations, and share with others.  

This PR covers 
- Workspace crud
- Updating Readonlyrest routing code to route to a workspaces
- Updating kibana fixtures (i.e seeding), now we need to seed a workspace, not a fire department 
- Removal of kibana permissions on the user.  The permissions now need to be tied to the workspace.  

Remaining tasks
- [x] create migration script for prod, which will:
1.  create a default workspace for every existing department
2.  for each department user, assign them to default workspace and assign appropriate permissions (admin, rw, etc)
3.  for each department admin, assign them to default workspace as owners
4.  copy all kibana_{id} indices to kibana_{id}_default

- [ ] Create user guide

In the meantime, please start reviewing.

### CODE REVIEW

**Comment by chopchop505** [comment]
When clicking dashboard, user is now presented with workspaces
image

They can manage workspace (deleting is a non fatal delete, where we just flag it as deleted)

image

Creating a new workspace:
image

Assigning users:
image

**Comment by larskendall** [comment]
Ok, so I have a big list of notes, but most of it is pretty nitpicky and little polish features. Overall, the functionality and everything is looking great. There are lots of little styling details that could use some tweaking, but I'd be happy to take a styling pass on this and work on them after you submit the PR.

I'll mark any notes that I think should be addressed for this PR with (!!!), and any that aren't critical but might be worth fixing now with a (!). The rest are mostly just notes for things that I can work on after this PR. I figured I'd just paste them all in.

## Functionality
  - (!!!) Before hitting the "Finish" button I changed pages and the workspace was still created, which was very surprising. I'd expect the workspace to only get created after hitting "Finish". Otherwise it should be very clearly communicated that the workspace is being created in the first step. If we do make "Finish" create it, then we need a "Back" button to return to the first step.
## Styling
  - Having the "Dashboard" button in the sidebar take you to "Workspaces" feels confusing. Maybe we should change the "Dashboard" button to "Workspaces" for anyone this update applies to.
  - **Dashboard / Workspaces**
    - (!!!) Typo in header at "Station Dasbhoards"
    - The header is a bit large... maybe we could reduce the vertical padding a little bit, or plan to make this a temporary header. Eventually the help info could be in a tooltip.
    - (!) "Manage workspaces" button should use capital casing
    - "Manage workspaces" button might look better to the right of "Your workspaces"
  - **Manage Workspaces**
    - Loading spinner should be displayed while workspaces load
    - Dropdown text colors (ie. green/red) are inconsistent with other places in the app which don't use colors. We should stick with colors or no colors. I'd lean toward no colors, since they can look a little tacky on text. The check/x icons already signal what the colors are conveying.
    - (!) Delete modal should use red "Delete" button in place of "Confirm"
    - We probably need a different icon than the checkmark for "Edit"
    - (!) We should change "Num of Users" to "# Users"
    - Deleting a workspace should show a loading indicator while the workspaces table refreshes
  - **Create New**
    - (!!!) New workspace page title and breadcrumbs should be "New Workspace" instead of "Edit Workspace". I guess it's the same UI as the edit flow, but it needs to be differentiated or else it looks broken.
    - (!) New workspace buttons should use square style for consistency with app
    - (!) Selecting a color should close the color selection dropdown
    - Checkbox highlight is too tall
    - We could potentially use the new on/off switch for the checkbox and change the text to read Yes/No
    - There doesn't seem to be a limit to the description length
  - **Workspace Users**
    - Help text might be better in tooltips. It currently bumps the actual UI way down the page.
    - Same dropdown text color issue
    - (!!!) Changing user settings hides the table for about one second.
    - (!) "Finish" button might make more sense at the bottom of the page

**Comment by chopchop505** [comment]
Thank you for feedback! You're the man and attention to detail is outstanding.  I'll work most of these issues, and update PR

**Comment by larskendall** [comment]
For the **Workspace Users** page, it might be nice if the help text is contained in a modal that you can open with a "Help" button somewhere. There's so much info there that it may not be feasible to fit it all into tooltips, and it's probably going to look a little awkward and intimidating sitting anywhere in that page.

**Comment by chopchop505** [comment]
- [ ] Deploy ES updates
- [ ] Deploy email updates 
- [ ] Run migration script

**Comment by chopchop505** [comment]
@larskendall I reworked the flow a little bit.  The only items I didn't address are:

- [ ] Renaming dashboards to workspaces.  I agree its confusing, but I'm also afraid users are going to get lost if they don't see the dashboard utton.  Maybe after a week or so, we rename?  Got any other ideas? 
- [ ] I didn't do anything about the giant wall of text on manager users.  I agree theres probably a better way of presenting the info, but I want to guarantee users to read it at least for this first rollout.

**Comment by larskendall** [comment]
@chopchop505 I think that makes sense. Should I re-review this PR, or are you still working on changes?

**Comment by chopchop505** [comment]
You can review

**Pull request closed without merging**
