### PR TITLE
Make Yesterday's Recap tabs clearer.

### PR DESCRIPTION
**Pull request by larskendall**
## Before
Screen Shot 2019-10-04 at 3 58 01 PM

## After
Screen Shot 2019-10-04 at 3 59 32 PM

### CODE REVIEW

**Comment by chopchop505** [comment]
Is it weird/bad-practice that the selected tab color font (white) is different than the non-selected one (black)

**Comment by chopchop505** [comment]
What do you think of an underline?

image

**Comment by chopchop505** [comment]
And a hover, more like this:
g3Ko9e2ysg

**Comment by larskendall** [comment]
I think it's pretty standard for the unselected tab to have a different color. Here's Ionic's segment button for reference, which is styled based off of the native platforms. The iOS style is very similar to how I set this up...

https://ionicframework.com/docs/api/segment

However, it's a valid point that with only two items it's a little bit ambiguous which one is selected. I think we're ok in this case, partly because people typically assume the darker one is selected, but also because there are rounded edges on the selected item, which I think helps make it a _little_ bit clearer.

My issue with doing an underlined selection in this case is that it doesn't address the issue I was trying to solve here, where you can't even tell the other item is a tab rather than some weird floating label. The Android style in that Ionic demo works that way, and I think it looks ok, but I prefer the iOS solution.

**Comment by chopchop505** [comment]
Allright, you win :)  Can you resolve the conflict and then its good to go

**Comment by larskendall** [comment]
:trophy:

Should be resolved now.

**Pull request merged**
